#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options:
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : Quantum Metrology with Photoelectrons Vol. 3 *Analysis methodologies*  # The title of the book. Will be placed in the left navbar.
author                      : Paul Hockett  # The author of the book
copyright                   : "2022"  # Copyright year to be placed in the footer
logo                        : ePSproc_logo.png  # A path to the book logo

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
# 26/01/22: quick test with 'auto' setting seemed to run notebooks even when already executed - leave 'off' for now...
execute:
  execute_notebooks: off

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: QM3.tex

# Add a bibtex file so that we can create citations
# NOTE - biblatex doesn't work!
# Backend is handled by Sphinxcontrib-bibtex, https://sphinxcontrib-bibtex.readthedocs.io/en/latest/quickstart.html
bibtex_bibfiles:
#  - bibs/book_IOP_quant_met_bbt_biblatex_051122.bib
#  - bibs/MF_recon_manuscript_June2020_bbt_biblatex_051122.bib
  - bibs/MF_recon_manuscript_June2020_bbt_bibtex_071122.bib
#  - references.bib  # Sample file

# Information about where the book exists on the web
repository:
  url: https://github.com/phockett/Quantum-Metrology-with-Photoelectrons-Vol3  # Online location of your book
  path_to_book: doc-source  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

# Additional Sphinx customisation for Latex output
# See https://jupyterbook.org/advanced/pdf.html#customize-latex-via-sphinx
sphinx:
  config:
    latex_toplevel_sectioning: 'part'
    # For plotly, see https://jupyterbook.org/en/stable/interactive/interactive.html#plotly
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    # Use MathJax v3, see https://jupyterbook.org/en/stable/content/math.html#math-and-equations
    # mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# For latex maths, per https://jupyterbook.org/en/stable/content/math.html#latex-style-math
parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - amsmath