#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options:
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : Quantum Metrology with Photoelectrons Vol. 3 *Analysis methodologies*  # The title of the book. Will be placed in the left navbar.
author                      : Paul Hockett with Varun Makhija  # The author of the book
copyright                   : "2022"  # Copyright year to be placed in the footer
logo                        : ePSproc_logo.png  # A path to the book logo
only_build_toc_files        : true  # Skip processing all other files, e.g. backup versions etc.

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
# 26/01/22: quick test with 'auto' setting seemed to run notebooks even when already executed - leave 'off' for now... can also set to 'force'
# For builds with old test docs also need to leave off, otherwise likely get build errors!
# 10/11/22: NOTE for docs with .md and .ipynb versions, only former seems to be used UNLESS execute is on (even if file ending included in ToC) - seems odd?
# 22/11/22 Quick test with cache is OK for quick HTML builds, and text updates, but can cause issues otherwise.
# 01/05/23 Reinstated cache, should be OK for temp builds with script which start from clean dir config... for additional options see https://jupyterbook.org/en/stable/content/execute.html#caching-the-notebook-execution 
# TODO - set this from a switch?
execute:
  # 27/04/23 - added arb timeout in s here, some fitting notebooks not completing?
  timeout: 1000
  execute_notebooks: 'force'
  # execute_notebooks: 'cache'
  
# exclude_patterns: [part1/*.md]   # This also doesn't work for skipping .md versions.

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: QM3.tex

# Add a bibtex file so that we can create citations
# NOTE - biblatex doesn't work!
# NOTE - for multiple .bib files, they will NOT BE PARSED if duplicate entries are found. Might be a fix for this...?
# Backend is handled by Sphinxcontrib-bibtex, https://sphinxcontrib-bibtex.readthedocs.io/en/latest/quickstart.html
bibtex_bibfiles:
#  - bibs/book_IOP_quant_met_bbt_biblatex_051122.bib
#  - bibs/MF_recon_manuscript_June2020_bbt_biblatex_051122.bib
# Test/initial files
  # - bibs/MF_recon_manuscript_June2020_bbt_bibtex_071122.bib
  # - bibs/hockett_pubs_bbt_bibtex_091122.bib
  # - bibs/MF_recon_manuscript_June2020_bbt_biblatex_211122.bib
  # - bibs/MF_recon_manuscript_June2020_bbt_bibtex_200123.bib
# Ongoing bib
  # 23/04/23 - auto-updating from Zotero on Stimpy.
  - bibs/MF_recon_manuscript_June2020_bbt_bibtex_ongoing.bib
  # 27/04/23 added for rot wavepacket refs.
  # NOTE - this is NOT in Zotero!
  - bibs/new_refs_jpbreview_VM_020323.bib
  # - bibs/QM3_ongoing.bib
#  - references.bib  # Sample file

# bibtex_reference_style: unsrt   # This fails? Needs to be nested somewhere? OK per-doc.
# bibtex_reference_style: author_year   # Default case

# Information about where the book exists on the web
repository:
  url: https://github.com/phockett/Quantum-Metrology-with-Photoelectrons-Vol3  # Online location of your book
  path_to_book: doc-source  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

# Additional Sphinx customisation for Latex output
# See https://jupyterbook.org/advanced/pdf.html#customize-latex-via-sphinx
sphinx:
  config:
    latex_toplevel_sectioning: 'part'
    # For plotly, see https://jupyterbook.org/en/stable/interactive/interactive.html#plotly
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    # Use MathJax v3, see https://jupyterbook.org/en/stable/content/math.html#math-and-equations - NOT REQUIRED IN SPHINX >4, see https://www.sphinx-doc.org/en/master/usage/extensions/math.html#module-sphinx.ext.mathjaxS
    # mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    # bibtex_reference_style: unsrt   # This fails at build, "failed: plugin sphinxcontrib.bibtex.style.referencing.unsrt not found"? Works OK in single docs?
                                      # Issue is that it's not a valid sphinxcontrib-bibtex style? https://sphinxcontrib-bibtex.readthedocs.io/en/latest/usage.html#referencing-style
                                      # But IS ok in local bib, https://sphinxcontrib-bibtex.readthedocs.io/en/latest/usage.html#directive-option-bibliography-style

    # Sphinx Latex customisation, see https://www.sphinx-doc.org/en/master/latex.html
    
    # Fixes for Pandas tabular outputs, see https://github.com/executablebooks/jupyter-book/issues/1553#issuecomment-998822118
    latex_elements:
      # Note this line cheats the table parameter into the documentclass[] parameter
      papersize: letterpaper,table
      # These lines add the desired packages to the latex build
      preamble: |+
        \nonstopmode   % 23/03/23 added to skip current Qutip build issues, but should be careful with this, and fix properly! See https://tex.stackexchange.com/questions/140845/how-can-i-ignore-latex-error-while-compiling
        \usepackage{xcolor}
        \usepackage{booktabs}
        \usepackage{multirow}
        % make phantomsection empty inside figures, see https://sphinxcontrib-bibtex.readthedocs.io/en/latest/usage.html#latex-backend-fails-with-citations-in-figure-captions
        \usepackage{etoolbox}
        % \AtBeginEnvironment{figure}{\renewcommand{\phantomsection}{}}  % Doesn't fix - old version?
        \AtBeginEnvironment{figure}{\pretocmd{\hyperlink}{\protect}{}{}}  % WORKING From https://github.com/mcmtroffaes/sphinxcontrib-bibtex/issues/276#issuecomment-1102154800, see also https://github.com/executablebooks/jupyter-book/issues/1710#issuecomment-1331323071
        %
        % ****** MORE MATHS RENDER TESTS, all failing.
        % Trying to fix `\bar{\varUpsilon}` gives `! Internal error: bad native font flag in `map_char_to_glyph'`
        % WORK AROUND, use \bar{\varUpsilon_{}} instead.
        % ** Fix hat issues, from https://tex.stackexchange.com/a/70498 - FAILS
        % \def\acc@hat{\mbox{\raisebox{-1.27ex}[0ex][0ex]{\^{}}}}
        % \renewcommand*\hat[1]{\placeaccent{\acc@hat}{#1}}
        % ** Testing more maths stuff, from https://tex.stackexchange.com/questions/578375/mathcal-incompatible-with-unicode-math
        % \usepackage{unicode-math}
        % \setmathfont{XITS Math}[Scale = MatchUppercase ]
        % \setmathfont{Latin Modern Math}[range = {cal,bfcal},Scale = MatchUppercase ]
        % ** Similar from https://tex.stackexchange.com/questions/227033/why-cant-i-use-my-font-with-unicode-math
        % \usepackage{unicode-math}
        % \setmathfont{Latin Modern Math}
        % \usepackage{mathspec}
        % \setmathfont(Latin,Digits,Greek){Latin Modern Sans}
        % \setmathrm{Latin Modern Sans}
        % ** Per https://github.com/wspr/unicode-math/issues/400 
        % \usepackage[mathbf=sym]{unicode-math}
        % ** Per https://tex.stackexchange.com/questions/159785/caveats-of-newtxmath-and-fontspec-together
        % \usepackage[no-math]{fontspec}
        % \usepackage[libertine]{newtxmath}
        
    # latex_elements:
      # preamble: '\usepackage{bm}'
      # - '\usepackage{bm}'
      # - '\usepackage{pxfonts}'
      # preamble: r'''\usepackage{bm}\usepackage{pxfonts}'''   # Not sure how to add multiple things here? '-' or list style not working? SEE https://github.com/executablebooks/jupyter-book/issues/1553#issuecomment-998822118
      # preamble: '\usepackage{bm}'   # For \bm, but causes other issues? Seems to break e.g. \hat{\mathbf{\mu}}?
    #  preamble: '\setmathfont{STIX Two Math}'  # Testing per bold with hat, https://tex.stackexchange.com/questions/381604/bold-math-with-hat FAILS
    # preamble: '\usepackage{unicode-math}'   # Already set by JupyterBook - not sure if this is causing issues...
    # preamble: '\usepackage{pxfonts}'
      # preamble: '\usepackage{amsfonts}'
      
    # For PD fixes, see https://github.com/executablebooks/jupyter-book/issues/1553#issuecomment-998822118
      # preamble: |+
      #   \usepackage{xcolor}
      #   \usepackage{booktabs}
      #   \usepackage{multirow}

    #*** MyST-NB settings
    # Merge stdout streams, https://myst-nb.readthedocs.io/en/latest/render/format_code_cells.html#group-into-single-streams
    nb_merge_streams: True
    
    #*** Mathjax config, see https://jupyterbook.org/en/stable/advanced/sphinx.html#defining-tex-macros
    # For Sphinx >= 4.0 set as "mathjax3_config" (was "mathjax_config"), updated 28/07/23
    mathjax3_config:
      tex:
        macros:
            # Fix for \bm, see https://github.com/mathjax/MathJax/issues/1219#issuecomment-341059843
            "bm": ["\\boldsymbol{#1}",1]

# For latex maths, per https://jupyterbook.org/en/stable/content/math.html#latex-style-math
parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    # default extensions to enable in the myst parser. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    - amsmath
    - colon_fence
    # - deflist
    - dollarmath
    # - html_admonition
    # - html_image
    - linkify
    # - replacements
    # - smartquotes
    - substitution
    - tasklist
    
  # Global substitutions, see https://jupyterbook.org/en/stable/content/content-blocks.html?highlight=substitutions#define-substitutions-for-your-whole-book
  # Not currently working? URLs break build, and basic not working either?
  # UPDATE: fixed by (a) adding substitution to list above (seems to OVERWRITE defaults) and (b) "" for links/active text (otherwise get build syntax errors), seems to render OK.
  myst_substitutions:
    # Ref sets
    QM1: "_Quantum Metrology_ Vol. 1 {cite}`hockett2018QMP1`"
    QM2: "_Quantum Metrology_ Vol. 2 {cite}`hockett2018QMP2`"
    QM12: "_Quantum Metrology_ Vols. 1 & 2 {cite}`hockett2018QMP1, hockett2018QMP2`"
    book_HTML: "[_Quantum Metrology_ Vol. 3 (HTML version)](https://phockett.github.io/Quantum-Metrology-with-Photoelectrons-Vol3/part1/main_intro_051122.html)"
    book_repo: "[_Quantum Metrology_ Vol. 3 (Github repo)](https://github.com/phockett/Quantum-Metrology-with-Photoelectrons-Vol3)"
    PEMtk_repo: "[Photoelectron Metrology Toolkit](https://github.com/phockett/PEMtk) {cite}`hockett2021PEMtkGithub`"
    PEMtk_docs: "[PEMtk documentation](https://pemtk.readthedocs.io) {cite}`hockett2021PEMtkDocs`"
    ePSproc_full: "[ePSproc codebase](https://epsproc.readthedocs.io) {cite}`hockett2016EPSprocAuthorea,ePSprocGithub,ePSprocDocs`"
    ePSproc_repo: "[ePSproc](https://github.com/phockett/ePSproc) {cite}`ePSprocGithub`"
    ePSproc_docs: "[ePSproc documentation](https://epsproc.readthedocs.io) {cite}`ePSprocDocs`"
    ePSdata_docs: "[ePSdata](https://phockett.github.io/ePSdata/about.html) {cite}`hockett2019EPSDataPhotoionization`"
    ePSdata_repo: "[ePSdata](https://github.com/phockett/ePSdata/) {cite}`hockett2019EPSDataPhotoionization`"
    ePSdata_zenodo: "[ePSdata Zenodo](https://zenodo.org/search?page=1&size=20&q=hockett&keywords=Data) {cite}`hockett2019EPSdataRepositoriesZenodo`"
    open_photo_stacks_repo: "[Open Photoionization Docker Stacks](https://github.com/phockett/open-photoionization-docker-stacks) {cite}`hockettOpenPhotoionizationDocker`"
    ePS_manual: "[ePolyScat website and manual](https://epolyscat.droppages.com/) {cite}`luccheseEPolyScatUserManual`"
    ePS_full: "[ePolyScat (ePS)](https://epolyscat.droppages.com/) {cite}`Lucchese1986,Gianturco1994,Natalense1999,luccheseEPolyScatUserManual`"
    libmsym: "[`libmsym`](https://github.com/mcodev31/libmsym) {cite}`johansson2017AutomaticProcedureGeneratinga,johansson2022LibmsymGithub`"
    lmfit: "[`lmfit` library](https://lmfit.github.io/lmfit-py/intro.html) {cite}`LMFITDocumentation, newville2014LMFITNonLinearLeastSquare`"
    shtools: "[`pySHtools`](https://shtools.oca.eu) {cite}`SHtoolsGithub, wieczorek2018SHToolsToolsWorking,wieczorek2019SHTOOLSSHTOOLSVersion, wieczorek2022SHtoolsDocs`"
    qutipFull: "[the `QuTiP` (_Quantum Toolkbox in Python_) library](https://qutip.org/) {cite}` johansson2012QuTiPOpensourcePython, johansson2013QuTiPPythonFramework, QuTiPQuantumToolboxWebsite`"
    qutipDocs: "[the QuTiP documentation](https://qutip.org/) {cite}`QuTiPQuantumToolboxWebsite`"
    xarray:  "[`Xarray`](https://docs.xarray.dev) {cite}`hoyer2017XarrayNDLabeled,XarrayDocumentation`"
    scipy: "[`Scipy`](https://scipy.org/) {cite}`SciPy`"
    
    # Glossary terms
    MF: "{term}`MF`"
    LF: "{term}`LF`"
    AF: "{term}`AF`"
    PADs: "{term}`PADs`"
    betas: "{term}`anisotropy paramters`"
    ADMs: "{term}`ADMs`"
    MS: "{term}`MS`"
    PG: "{term}`PG`"
    HOMO: "{term}`HOMO`"
    RWP: "{term}`RWP`"
    GAMMACHANNEL: "{term}`channel functions`"
    RADMATE: "{term}`radial matrix elements`"
    SYMHARM: "{term}`symmetrized harmonics`"
    GEOMPARAMS: "{term}`geometric coupling parameters`"
    PARTIALWAVES: "{term}`partial-waves`"
    PARTIALWAVEEXP: "{term}`partial-wave expansion`"
    FRAMEROT: "{term}`frame rotation`"
    EULER: "{term}`Euler angles`"
    WIGNERD: "{term}`Wigner rotation matrix elements`"
    BOOTSTRAP: "{term}`bootstrap retrieval protocol`"
    
    # Maths shorthand
    # BLM: "$\beta_{L,M}$"  # This fails, seems to cut eqn, maybe drops first $?
    BLM: "$\\beta_{L,M}$"   # This works, note esc for \ IN MATHS seems required.
    BLMt: "$\\beta_{L,M}(t)$"
    ADMsymbol: "$A_{Q,S}^{K}(t)$"
    
    # Additional links/cross-refs
    PARTII: "{ref}`Part II <chpt:extracting-matrix-elements-overview>`"
    
    
# Global substitutions, see https://jupyterbook.org/en/stable/content/content-blocks.html?highlight=substitutions#define-substitutions-for-your-whole-book
# parse:
#   myst_substitutions:
#     # key: value
#     book_repo: [Quantum Metrology Vol. 3](https://github.com/phockett/Quantum-Metrology-with-Photoelectrons-Vol3)
#     PEMtk_repo: [Photoelectron Metrology Toolkit](https://github.com/phockett/PEMtk){cite}`hockett2021PEMtkGithub`

# Global substitutions, see https://jupyterbook.org/en/stable/content/content-blocks.html?highlight=substitutions#define-substitutions-for-your-whole-book
# Not currently working? URLs break build, and basic not working either?
# parse:
#   # key: value
#   myst_substitutions:
#     test_sub: Something
    # book_repo: [Quantum Metrology Vol](https://github.com/phockett/Quantum-Metrology-with-Photoelectrons-Vol3)
    
  # For URLs
# substitutions:
#   book_repo: [Quantum Metrology Vol](https://github.com/phockett/Quantum-Metrology-with-Photoelectrons-Vol3)
#   PEMtk_repo: [Photoelectron Metrology Toolkit](https://github.com/phockett/PEMtk){cite}`hockett2021PEMtkGithub`