#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options:
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : Quantum Metrology with Photoelectrons Vol. 3 *Analysis methodologies*  # The title of the book. Will be placed in the left navbar.
author                      : Paul Hockett  # The author of the book
copyright                   : "2022"  # Copyright year to be placed in the footer
logo                        : ePSproc_logo.png  # A path to the book logo
only_build_toc_files        : true  # Skip processing all other files, e.g. backup versions etc.

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
# 26/01/22: quick test with 'auto' setting seemed to run notebooks even when already executed - leave 'off' for now...
execute:
  execute_notebooks: off

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: QM3.tex

# Add a bibtex file so that we can create citations
# NOTE - biblatex doesn't work!
# Backend is handled by Sphinxcontrib-bibtex, https://sphinxcontrib-bibtex.readthedocs.io/en/latest/quickstart.html
bibtex_bibfiles:
#  - bibs/book_IOP_quant_met_bbt_biblatex_051122.bib
#  - bibs/MF_recon_manuscript_June2020_bbt_biblatex_051122.bib
# Test/initial files
  # - bibs/MF_recon_manuscript_June2020_bbt_bibtex_071122.bib
  # - bibs/hockett_pubs_bbt_bibtex_091122.bib
# Ongoing bib
  - bibs/QM3_ongoing.bib
#  - references.bib  # Sample file

# bibtex_reference_style: unsrt   # This fails? Needs to be nested somewhere? OK per-doc.
# bibtex_reference_style: author_year   # Default case

# Information about where the book exists on the web
repository:
  url: https://github.com/phockett/Quantum-Metrology-with-Photoelectrons-Vol3  # Online location of your book
  path_to_book: doc-source  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

# Additional Sphinx customisation for Latex output
# See https://jupyterbook.org/advanced/pdf.html#customize-latex-via-sphinx
sphinx:
  config:
    latex_toplevel_sectioning: 'part'
    # For plotly, see https://jupyterbook.org/en/stable/interactive/interactive.html#plotly
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    # Use MathJax v3, see https://jupyterbook.org/en/stable/content/math.html#math-and-equations
    # mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    # bibtex_reference_style: unsrt   # This fails at build, "failed: plugin sphinxcontrib.bibtex.style.referencing.unsrt not found"? Works OK in single docs?
                                      # Issue is that it's not a valid sphinxcontrib-bibtex style? https://sphinxcontrib-bibtex.readthedocs.io/en/latest/usage.html#referencing-style
                                      # But IS ok in local bib, https://sphinxcontrib-bibtex.readthedocs.io/en/latest/usage.html#directive-option-bibliography-style

    # Sphinx Latex customisation, see https://www.sphinx-doc.org/en/master/latex.html
    # latex_elements:
    #   preamble: '\usepackage{pxfonts}'

# For latex maths, per https://jupyterbook.org/en/stable/content/math.html#latex-style-math
parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    # default extensions to enable in the myst parser. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    - amsmath
    - colon_fence
    # - deflist
    - dollarmath
    # - html_admonition
    # - html_image
    - linkify
    # - replacements
    # - smartquotes
    - substitution
    - tasklist
    
  # Global substitutions, see https://jupyterbook.org/en/stable/content/content-blocks.html?highlight=substitutions#define-substitutions-for-your-whole-book
  # Not currently working? URLs break build, and basic not working either?
  # UPDATE: fixed by (a) adding substitution to list above (seems to OVERWRITE defaults) and (b) "" for links/active text (otherwise get build syntax errors), seems to render OK.
  myst_substitutions:
    test_sub: "Something"
    PEMtk_repo: "[Photoelectron Metrology Toolkit](https://github.com/phockett/PEMtk) {cite}`hockett2021PEMtkGithub`"
    PEMtk_docs: "[PEMtk documentation](https://pemtk.readthedocs.io) {cite}`hockett2021PEMtkDocs`"
    ePSproc_full: "[ePSproc codebase](https://epsproc.readthedocs.io) {cite}`hockett2016EPSprocAuthorea,ePSprocGithub,ePSprocDocs`"
    ePSproc_repo: "[ePSproc](https://github.com/phockett/ePSproc) {cite}`ePSprocGithub`"
    ePSproc_docs: "[ePSproc documentation](https://epsproc.readthedocs.io) {cite}`ePSprocDocs`"
    book_repo: "[Quantum Metrology Vol. 3](https://github.com/phockett/Quantum-Metrology-with-Photoelectrons-Vol3)"
    open_photo_stacks_repo: "[Open Photoionization Docker Stacks](https://github.com/phockett/open-photoionization-docker-stacks) {cite}`hockettOpenPhotoionizationDocker`"
    ePS_manual: "[ePolyScat website and manual](https://epolyscat.droppages.com/) {cite}`luccheseEPolyScatUserManual`"
    ePS_full: "[ePolyScat (ePS)](https://epolyscat.droppages.com/) {cite}`Lucchese1986,Gianturco1994,Natalense1999,luccheseEPolyScatUserManual`"
    
  # substitutions:
  #   book_repo: [Quantum Metrology Vol. 3](https://github.com/phockett/Quantum-Metrology-with-Photoelectrons-Vol3)
  #   PEMtk_repo: [Photoelectron Metrology Toolkit](https://github.com/phockett/PEMtk){cite}`hockett2021PEMtkGithub`
    
    
# Global substitutions, see https://jupyterbook.org/en/stable/content/content-blocks.html?highlight=substitutions#define-substitutions-for-your-whole-book
# parse:
#   myst_substitutions:
#     # key: value
#     book_repo: [Quantum Metrology Vol. 3](https://github.com/phockett/Quantum-Metrology-with-Photoelectrons-Vol3)
#     PEMtk_repo: [Photoelectron Metrology Toolkit](https://github.com/phockett/PEMtk){cite}`hockett2021PEMtkGithub`

# Global substitutions, see https://jupyterbook.org/en/stable/content/content-blocks.html?highlight=substitutions#define-substitutions-for-your-whole-book
# Not currently working? URLs break build, and basic not working either?
# parse:
#   # key: value
#   myst_substitutions:
#     test_sub: Something
    # book_repo: [Quantum Metrology Vol](https://github.com/phockett/Quantum-Metrology-with-Photoelectrons-Vol3)
    
  # For URLs
# substitutions:
#   book_repo: [Quantum Metrology Vol](https://github.com/phockett/Quantum-Metrology-with-Photoelectrons-Vol3)
#   PEMtk_repo: [Photoelectron Metrology Toolkit](https://github.com/phockett/PEMtk){cite}`hockett2021PEMtkGithub`